
CFLAGS = -Wall

all: prg-2.1 prg-2.2 prg-2.3 prg-2.4

prg-2.1: simple_alarm_clock.c
	$(CC) -o $@ $<

prg-2.2: multiple_alarm_clocks.c
	$(CC) -o $@ $<

prg-2.3: catch_the_zombies.c
	$(CC) -o $@ $<

prg-2.4: error_handling.c
	$(CC) -o $@ $<

.PHONY: all
